/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Corporation. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
package com.microsoft.services.graph;





/**
 * The type Attendee.
* @deprecated This SDK is deprecated. Please review the README for further information (https://github.com/OfficeDev/Microsoft-Graph-SDK-Android).
 */
@Deprecated
public class Attendee extends Recipient {

    public Attendee(){
        setODataType("#microsoft.graph.attendee");
    }

    private ResponseStatus status;

    /**
    * Gets the status.
    *
    * @return the ResponseStatus
    */
    public ResponseStatus getStatus() {
        return this.status; 
    }

    /**
    * Sets the status.
    *
    * @param value the ResponseStatus
    */
    public void setStatus(ResponseStatus value) { 
        this.status = value;
        valueChanged("status", value);

    }

    private AttendeeType type;

    /**
    * Gets the type.
    *
    * @return the AttendeeType
    */
    public AttendeeType getType() {
        return this.type; 
    }

    /**
    * Sets the type.
    *
    * @param value the AttendeeType
    */
    public void setType(AttendeeType value) { 
        this.type = value;
        valueChanged("type", value);

    }
}
