/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Corporation. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
package com.microsoft.services.graph;





/**
 * The type Calendar Group.
* @deprecated This SDK is deprecated. Please review the README for further information (https://github.com/OfficeDev/Microsoft-Graph-SDK-Android).
 */
@Deprecated
public class CalendarGroup extends Entity {

    public CalendarGroup(){
        setODataType("#microsoft.graph.calendarGroup");
    }
            
    private String name;
     
    /**
    * Gets the name.
    *
    * @return the String
    */
    public String getName() {
        return this.name; 
    }

    /**
    * Sets the name.
    *
    * @param value the String
    */
    public void setName(String value) { 
        this.name = value; 
        valueChanged("name", value);

    }
            
    private java.util.UUID classId;
     
    /**
    * Gets the class Id.
    *
    * @return the java.util.UUID
    */
    public java.util.UUID getClassId() {
        return this.classId; 
    }

    /**
    * Sets the class Id.
    *
    * @param value the java.util.UUID
    */
    public void setClassId(java.util.UUID value) { 
        this.classId = value; 
        valueChanged("classId", value);

    }
            
    private String changeKey;
     
    /**
    * Gets the change Key.
    *
    * @return the String
    */
    public String getChangeKey() {
        return this.changeKey; 
    }

    /**
    * Sets the change Key.
    *
    * @param value the String
    */
    public void setChangeKey(String value) { 
        this.changeKey = value; 
        valueChanged("changeKey", value);

    }
    
        
    private java.util.List<Calendar> calendars = null;
    
    
     
    /**
    * Gets the calendars.
    *
    * @return the java.util.List<Calendar>
    */
    public java.util.List<Calendar> getCalendars() {
        return this.calendars; 
    }

    /**
    * Sets the calendars.
    *
    * @param value the java.util.List<Calendar>
    */
    public void setCalendars(java.util.List<Calendar> value) { 
        this.calendars = value; 
        valueChanged("calendars", value);

    }
}

