/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Corporation. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
package com.microsoft.services.graph;





/**
 * The type Calendar.
*/
public class Calendar extends Entity {

    public Calendar(){
        setODataType("#microsoft.graph.calendar");
    }
            
    private String name;
     
    /**
    * Gets the name.
    *
    * @return the String
    */
    public String getName() {
        return this.name; 
    }

    /**
    * Sets the name.
    *
    * @param value the String
    */
    public void setName(String value) { 
        this.name = value; 
        valueChanged("name", value);

    }
            
    private CalendarColor color;
     
    /**
    * Gets the color.
    *
    * @return the CalendarColor
    */
    public CalendarColor getColor() {
        return this.color; 
    }

    /**
    * Sets the color.
    *
    * @param value the CalendarColor
    */
    public void setColor(CalendarColor value) { 
        this.color = value; 
        valueChanged("color", value);

    }
            
    private String changeKey;
     
    /**
    * Gets the change Key.
    *
    * @return the String
    */
    public String getChangeKey() {
        return this.changeKey; 
    }

    /**
    * Sets the change Key.
    *
    * @param value the String
    */
    public void setChangeKey(String value) { 
        this.changeKey = value; 
        valueChanged("changeKey", value);

    }
    
        
    private java.util.List<Event> events = null;
    
    
     
    /**
    * Gets the events.
    *
    * @return the java.util.List<Event>
    */
    public java.util.List<Event> getEvents() {
        return this.events; 
    }

    /**
    * Sets the events.
    *
    * @param value the java.util.List<Event>
    */
    public void setEvents(java.util.List<Event> value) { 
        this.events = value; 
        valueChanged("events", value);

    }
    
        
    private java.util.List<Event> calendarView = null;
    
    
     
    /**
    * Gets the calendar View.
    *
    * @return the java.util.List<Event>
    */
    public java.util.List<Event> getCalendarView() {
        return this.calendarView; 
    }

    /**
    * Sets the calendar View.
    *
    * @param value the java.util.List<Event>
    */
    public void setCalendarView(java.util.List<Event> value) { 
        this.calendarView = value; 
        valueChanged("calendarView", value);

    }
}

