/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Corporation. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
package com.microsoft.services.graph;

import com.microsoft.services.orc.core.ODataBaseEntity;




/**
 * The type Date Time Time Zone.
* @deprecated This SDK is deprecated. Please review the README for further information (https://github.com/OfficeDev/Microsoft-Graph-SDK-Android).
 */
@Deprecated
public class DateTimeTimeZone extends ODataBaseEntity {

    public DateTimeTimeZone(){
        setODataType("#microsoft.graph.dateTimeTimeZone");
    }

    private String dateTime;

    /**
    * Gets the date Time.
    *
    * @return the String
    */
    public String getDateTime() {
        return this.dateTime; 
    }

    /**
    * Sets the date Time.
    *
    * @param value the String
    */
    public void setDateTime(String value) { 
        this.dateTime = value;
        valueChanged("dateTime", value);

    }

    private String timeZone;

    /**
    * Gets the time Zone.
    *
    * @return the String
    */
    public String getTimeZone() {
        return this.timeZone; 
    }

    /**
    * Sets the time Zone.
    *
    * @param value the String
    */
    public void setTimeZone(String value) { 
        this.timeZone = value;
        valueChanged("timeZone", value);

    }
}
