/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
package com.microsoft.services.graph;





/**
 * The type Event.
*/
public class Event extends OutlookItem {

    public Event(){
        setODataType("#microsoft.graph.event");
    }
            
    private String originalStartTimeZone;
     
    /**
    * Gets the original Start Time Zone.
    *
    * @return the String
    */
    public String getOriginalStartTimeZone() {
        return this.originalStartTimeZone; 
    }

    /**
    * Sets the original Start Time Zone.
    *
    * @param value the String
    */
    public void setOriginalStartTimeZone(String value) { 
        this.originalStartTimeZone = value; 
        valueChanged("originalStartTimeZone", value);

    }
            
    private String originalEndTimeZone;
     
    /**
    * Gets the original End Time Zone.
    *
    * @return the String
    */
    public String getOriginalEndTimeZone() {
        return this.originalEndTimeZone; 
    }

    /**
    * Sets the original End Time Zone.
    *
    * @param value the String
    */
    public void setOriginalEndTimeZone(String value) { 
        this.originalEndTimeZone = value; 
        valueChanged("originalEndTimeZone", value);

    }
            
    private ResponseStatus responseStatus;
     
    /**
    * Gets the response Status.
    *
    * @return the ResponseStatus
    */
    public ResponseStatus getResponseStatus() {
        return this.responseStatus; 
    }

    /**
    * Sets the response Status.
    *
    * @param value the ResponseStatus
    */
    public void setResponseStatus(ResponseStatus value) { 
        this.responseStatus = value; 
        valueChanged("responseStatus", value);

    }
            
    private String iCalUId;
     
    /**
    * Gets the i Cal UId.
    *
    * @return the String
    */
    public String getICalUId() {
        return this.iCalUId; 
    }

    /**
    * Sets the i Cal UId.
    *
    * @param value the String
    */
    public void setICalUId(String value) { 
        this.iCalUId = value; 
        valueChanged("iCalUId", value);

    }
            
    private Integer reminderMinutesBeforeStart;
     
    /**
    * Gets the reminder Minutes Before Start.
    *
    * @return the Integer
    */
    public Integer getReminderMinutesBeforeStart() {
        return this.reminderMinutesBeforeStart; 
    }

    /**
    * Sets the reminder Minutes Before Start.
    *
    * @param value the Integer
    */
    public void setReminderMinutesBeforeStart(Integer value) { 
        this.reminderMinutesBeforeStart = value; 
        valueChanged("reminderMinutesBeforeStart", value);

    }
            
    private Boolean isReminderOn;
     
    /**
    * Gets the is Reminder On.
    *
    * @return the Boolean
    */
    public Boolean getIsReminderOn() {
        return this.isReminderOn; 
    }

    /**
    * Sets the is Reminder On.
    *
    * @param value the Boolean
    */
    public void setIsReminderOn(Boolean value) { 
        this.isReminderOn = value; 
        valueChanged("isReminderOn", value);

    }
            
    private Boolean hasAttachments;
     
    /**
    * Gets the has Attachments.
    *
    * @return the Boolean
    */
    public Boolean getHasAttachments() {
        return this.hasAttachments; 
    }

    /**
    * Sets the has Attachments.
    *
    * @param value the Boolean
    */
    public void setHasAttachments(Boolean value) { 
        this.hasAttachments = value; 
        valueChanged("hasAttachments", value);

    }
            
    private String subject;
     
    /**
    * Gets the subject.
    *
    * @return the String
    */
    public String getSubject() {
        return this.subject; 
    }

    /**
    * Sets the subject.
    *
    * @param value the String
    */
    public void setSubject(String value) { 
        this.subject = value; 
        valueChanged("subject", value);

    }
            
    private ItemBody body;
     
    /**
    * Gets the body.
    *
    * @return the ItemBody
    */
    public ItemBody getBody() {
        return this.body; 
    }

    /**
    * Sets the body.
    *
    * @param value the ItemBody
    */
    public void setBody(ItemBody value) { 
        this.body = value; 
        valueChanged("body", value);

    }
            
    private String bodyPreview;
     
    /**
    * Gets the body Preview.
    *
    * @return the String
    */
    public String getBodyPreview() {
        return this.bodyPreview; 
    }

    /**
    * Sets the body Preview.
    *
    * @param value the String
    */
    public void setBodyPreview(String value) { 
        this.bodyPreview = value; 
        valueChanged("bodyPreview", value);

    }
            
    private Importance importance;
     
    /**
    * Gets the importance.
    *
    * @return the Importance
    */
    public Importance getImportance() {
        return this.importance; 
    }

    /**
    * Sets the importance.
    *
    * @param value the Importance
    */
    public void setImportance(Importance value) { 
        this.importance = value; 
        valueChanged("importance", value);

    }
            
    private Sensitivity sensitivity;
     
    /**
    * Gets the sensitivity.
    *
    * @return the Sensitivity
    */
    public Sensitivity getSensitivity() {
        return this.sensitivity; 
    }

    /**
    * Sets the sensitivity.
    *
    * @param value the Sensitivity
    */
    public void setSensitivity(Sensitivity value) { 
        this.sensitivity = value; 
        valueChanged("sensitivity", value);

    }
            
    private DateTimeTimeZone start;
     
    /**
    * Gets the start.
    *
    * @return the DateTimeTimeZone
    */
    public DateTimeTimeZone getStart() {
        return this.start; 
    }

    /**
    * Sets the start.
    *
    * @param value the DateTimeTimeZone
    */
    public void setStart(DateTimeTimeZone value) { 
        this.start = value; 
        valueChanged("start", value);

    }
            
    private java.util.Calendar originalStart;
     
    /**
    * Gets the original Start.
    *
    * @return the java.util.Calendar
    */
    public java.util.Calendar getOriginalStart() {
        return this.originalStart; 
    }

    /**
    * Sets the original Start.
    *
    * @param value the java.util.Calendar
    */
    public void setOriginalStart(java.util.Calendar value) { 
        this.originalStart = value; 
        valueChanged("originalStart", value);

    }
            
    private DateTimeTimeZone end;
     
    /**
    * Gets the end.
    *
    * @return the DateTimeTimeZone
    */
    public DateTimeTimeZone getEnd() {
        return this.end; 
    }

    /**
    * Sets the end.
    *
    * @param value the DateTimeTimeZone
    */
    public void setEnd(DateTimeTimeZone value) { 
        this.end = value; 
        valueChanged("end", value);

    }
            
    private Location location;
     
    /**
    * Gets the location.
    *
    * @return the Location
    */
    public Location getLocation() {
        return this.location; 
    }

    /**
    * Sets the location.
    *
    * @param value the Location
    */
    public void setLocation(Location value) { 
        this.location = value; 
        valueChanged("location", value);

    }
            
    private Boolean isAllDay;
     
    /**
    * Gets the is All Day.
    *
    * @return the Boolean
    */
    public Boolean getIsAllDay() {
        return this.isAllDay; 
    }

    /**
    * Sets the is All Day.
    *
    * @param value the Boolean
    */
    public void setIsAllDay(Boolean value) { 
        this.isAllDay = value; 
        valueChanged("isAllDay", value);

    }
            
    private Boolean isCancelled;
     
    /**
    * Gets the is Cancelled.
    *
    * @return the Boolean
    */
    public Boolean getIsCancelled() {
        return this.isCancelled; 
    }

    /**
    * Sets the is Cancelled.
    *
    * @param value the Boolean
    */
    public void setIsCancelled(Boolean value) { 
        this.isCancelled = value; 
        valueChanged("isCancelled", value);

    }
            
    private Boolean isOrganizer;
     
    /**
    * Gets the is Organizer.
    *
    * @return the Boolean
    */
    public Boolean getIsOrganizer() {
        return this.isOrganizer; 
    }

    /**
    * Sets the is Organizer.
    *
    * @param value the Boolean
    */
    public void setIsOrganizer(Boolean value) { 
        this.isOrganizer = value; 
        valueChanged("isOrganizer", value);

    }
            
    private PatternedRecurrence recurrence;
     
    /**
    * Gets the recurrence.
    *
    * @return the PatternedRecurrence
    */
    public PatternedRecurrence getRecurrence() {
        return this.recurrence; 
    }

    /**
    * Sets the recurrence.
    *
    * @param value the PatternedRecurrence
    */
    public void setRecurrence(PatternedRecurrence value) { 
        this.recurrence = value; 
        valueChanged("recurrence", value);

    }
            
    private Boolean responseRequested;
     
    /**
    * Gets the response Requested.
    *
    * @return the Boolean
    */
    public Boolean getResponseRequested() {
        return this.responseRequested; 
    }

    /**
    * Sets the response Requested.
    *
    * @param value the Boolean
    */
    public void setResponseRequested(Boolean value) { 
        this.responseRequested = value; 
        valueChanged("responseRequested", value);

    }
            
    private String seriesMasterId;
     
    /**
    * Gets the series Master Id.
    *
    * @return the String
    */
    public String getSeriesMasterId() {
        return this.seriesMasterId; 
    }

    /**
    * Sets the series Master Id.
    *
    * @param value the String
    */
    public void setSeriesMasterId(String value) { 
        this.seriesMasterId = value; 
        valueChanged("seriesMasterId", value);

    }
            
    private FreeBusyStatus showAs;
     
    /**
    * Gets the show As.
    *
    * @return the FreeBusyStatus
    */
    public FreeBusyStatus getShowAs() {
        return this.showAs; 
    }

    /**
    * Sets the show As.
    *
    * @param value the FreeBusyStatus
    */
    public void setShowAs(FreeBusyStatus value) { 
        this.showAs = value; 
        valueChanged("showAs", value);

    }
            
    private EventType type;
     
    /**
    * Gets the type.
    *
    * @return the EventType
    */
    public EventType getType() {
        return this.type; 
    }

    /**
    * Sets the type.
    *
    * @param value the EventType
    */
    public void setType(EventType value) { 
        this.type = value; 
        valueChanged("type", value);

    }
    
        
    private java.util.List<Attendee> attendees = null;
    
    
     
    /**
    * Gets the attendees.
    *
    * @return the java.util.List<Attendee>
    */
    public java.util.List<Attendee> getAttendees() {
        return this.attendees; 
    }

    /**
    * Sets the attendees.
    *
    * @param value the java.util.List<Attendee>
    */
    public void setAttendees(java.util.List<Attendee> value) { 
        this.attendees = value; 
        valueChanged("attendees", value);

    }
            
    private Recipient organizer;
     
    /**
    * Gets the organizer.
    *
    * @return the Recipient
    */
    public Recipient getOrganizer() {
        return this.organizer; 
    }

    /**
    * Sets the organizer.
    *
    * @param value the Recipient
    */
    public void setOrganizer(Recipient value) { 
        this.organizer = value; 
        valueChanged("organizer", value);

    }
            
    private String webLink;
     
    /**
    * Gets the web Link.
    *
    * @return the String
    */
    public String getWebLink() {
        return this.webLink; 
    }

    /**
    * Sets the web Link.
    *
    * @param value the String
    */
    public void setWebLink(String value) { 
        this.webLink = value; 
        valueChanged("webLink", value);

    }
            
    private Calendar calendar;
     
    /**
    * Gets the calendar.
    *
    * @return the Calendar
    */
    public Calendar getCalendar() {
        return this.calendar; 
    }

    /**
    * Sets the calendar.
    *
    * @param value the Calendar
    */
    public void setCalendar(Calendar value) { 
        this.calendar = value; 
        valueChanged("calendar", value);

    }
    
        
    private java.util.List<Event> instances = null;
    
    
     
    /**
    * Gets the instances.
    *
    * @return the java.util.List<Event>
    */
    public java.util.List<Event> getInstances() {
        return this.instances; 
    }

    /**
    * Sets the instances.
    *
    * @param value the java.util.List<Event>
    */
    public void setInstances(java.util.List<Event> value) { 
        this.instances = value; 
        valueChanged("instances", value);

    }
    
        
    private java.util.List<Attachment> attachments = null;
    
    
     
    /**
    * Gets the attachments.
    *
    * @return the java.util.List<Attachment>
    */
    public java.util.List<Attachment> getAttachments() {
        return this.attachments; 
    }

    /**
    * Sets the attachments.
    *
    * @param value the java.util.List<Attachment>
    */
    public void setAttachments(java.util.List<Attachment> value) { 
        this.attachments = value; 
        valueChanged("attachments", value);

    }
}

