/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
package com.microsoft.services.graph;

import com.microsoft.services.orc.core.ODataBaseEntity;




/**
 * The type Location.
*/
public class Location extends ODataBaseEntity {

    public Location(){
        setODataType("#microsoft.graph.location");
    }

    private String displayName;

    /**
    * Gets the display Name.
    *
    * @return the String
    */
    public String getDisplayName() {
        return this.displayName; 
    }

    /**
    * Sets the display Name.
    *
    * @param value the String
    */
    public void setDisplayName(String value) { 
        this.displayName = value;
        valueChanged("displayName", value);

    }

    private PhysicalAddress address;

    /**
    * Gets the address.
    *
    * @return the PhysicalAddress
    */
    public PhysicalAddress getAddress() {
        return this.address; 
    }

    /**
    * Sets the address.
    *
    * @param value the PhysicalAddress
    */
    public void setAddress(PhysicalAddress value) { 
        this.address = value;
        valueChanged("address", value);

    }
}
