/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Corporation. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
package com.microsoft.services.graph;

import com.microsoft.services.orc.core.ODataBaseEntity;




/**
 * The type Patterned Recurrence.
* @deprecated This SDK is deprecated. Please review the README for further information (https://github.com/OfficeDev/Microsoft-Graph-SDK-Android).
 */
@Deprecated
public class PatternedRecurrence extends ODataBaseEntity {

    public PatternedRecurrence(){
        setODataType("#microsoft.graph.patternedRecurrence");
    }

    private RecurrencePattern pattern;

    /**
    * Gets the pattern.
    *
    * @return the RecurrencePattern
    */
    public RecurrencePattern getPattern() {
        return this.pattern; 
    }

    /**
    * Sets the pattern.
    *
    * @param value the RecurrencePattern
    */
    public void setPattern(RecurrencePattern value) { 
        this.pattern = value;
        valueChanged("pattern", value);

    }

    private RecurrenceRange range;

    /**
    * Gets the range.
    *
    * @return the RecurrenceRange
    */
    public RecurrenceRange getRange() {
        return this.range; 
    }

    /**
    * Sets the range.
    *
    * @param value the RecurrenceRange
    */
    public void setRange(RecurrenceRange value) { 
        this.range = value;
        valueChanged("range", value);

    }
}
