/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Corporation. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
package com.microsoft.services.graph;

import com.microsoft.services.orc.core.ODataBaseEntity;




/**
 * The type Physical Address.
* @deprecated This SDK is deprecated. Please review the README for further information (https://github.com/OfficeDev/Microsoft-Graph-SDK-Android).
 */
@Deprecated
public class PhysicalAddress extends ODataBaseEntity {

    public PhysicalAddress(){
        setODataType("#microsoft.graph.physicalAddress");
    }

    private String street;

    /**
    * Gets the street.
    *
    * @return the String
    */
    public String getStreet() {
        return this.street; 
    }

    /**
    * Sets the street.
    *
    * @param value the String
    */
    public void setStreet(String value) { 
        this.street = value;
        valueChanged("street", value);

    }

    private String city;

    /**
    * Gets the city.
    *
    * @return the String
    */
    public String getCity() {
        return this.city; 
    }

    /**
    * Sets the city.
    *
    * @param value the String
    */
    public void setCity(String value) { 
        this.city = value;
        valueChanged("city", value);

    }

    private String state;

    /**
    * Gets the state.
    *
    * @return the String
    */
    public String getState() {
        return this.state; 
    }

    /**
    * Sets the state.
    *
    * @param value the String
    */
    public void setState(String value) { 
        this.state = value;
        valueChanged("state", value);

    }

    private String countryOrRegion;

    /**
    * Gets the country Or Region.
    *
    * @return the String
    */
    public String getCountryOrRegion() {
        return this.countryOrRegion; 
    }

    /**
    * Sets the country Or Region.
    *
    * @param value the String
    */
    public void setCountryOrRegion(String value) { 
        this.countryOrRegion = value;
        valueChanged("countryOrRegion", value);

    }

    private String postalCode;

    /**
    * Gets the postal Code.
    *
    * @return the String
    */
    public String getPostalCode() {
        return this.postalCode; 
    }

    /**
    * Sets the postal Code.
    *
    * @param value the String
    */
    public void setPostalCode(String value) { 
        this.postalCode = value;
        valueChanged("postalCode", value);

    }
}
