/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Corporation. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
package com.microsoft.services.graph;





/**
 * The type Post.
*/
public class Post extends OutlookItem {

    public Post(){
        setODataType("#microsoft.graph.post");
    }
            
    private ItemBody body;
     
    /**
    * Gets the body.
    *
    * @return the ItemBody
    */
    public ItemBody getBody() {
        return this.body; 
    }

    /**
    * Sets the body.
    *
    * @param value the ItemBody
    */
    public void setBody(ItemBody value) { 
        this.body = value; 
        valueChanged("body", value);

    }
            
    private java.util.Calendar receivedDateTime;
     
    /**
    * Gets the received Date Time.
    *
    * @return the java.util.Calendar
    */
    public java.util.Calendar getReceivedDateTime() {
        return this.receivedDateTime; 
    }

    /**
    * Sets the received Date Time.
    *
    * @param value the java.util.Calendar
    */
    public void setReceivedDateTime(java.util.Calendar value) { 
        this.receivedDateTime = value; 
        valueChanged("receivedDateTime", value);

    }
            
    private Boolean hasAttachments;
     
    /**
    * Gets the has Attachments.
    *
    * @return the Boolean
    */
    public Boolean getHasAttachments() {
        return this.hasAttachments; 
    }

    /**
    * Sets the has Attachments.
    *
    * @param value the Boolean
    */
    public void setHasAttachments(Boolean value) { 
        this.hasAttachments = value; 
        valueChanged("hasAttachments", value);

    }
            
    private Recipient from;
     
    /**
    * Gets the from.
    *
    * @return the Recipient
    */
    public Recipient getFrom() {
        return this.from; 
    }

    /**
    * Sets the from.
    *
    * @param value the Recipient
    */
    public void setFrom(Recipient value) { 
        this.from = value; 
        valueChanged("from", value);

    }
            
    private Recipient sender;
     
    /**
    * Gets the sender.
    *
    * @return the Recipient
    */
    public Recipient getSender() {
        return this.sender; 
    }

    /**
    * Sets the sender.
    *
    * @param value the Recipient
    */
    public void setSender(Recipient value) { 
        this.sender = value; 
        valueChanged("sender", value);

    }
            
    private String conversationThreadId;
     
    /**
    * Gets the conversation Thread Id.
    *
    * @return the String
    */
    public String getConversationThreadId() {
        return this.conversationThreadId; 
    }

    /**
    * Sets the conversation Thread Id.
    *
    * @param value the String
    */
    public void setConversationThreadId(String value) { 
        this.conversationThreadId = value; 
        valueChanged("conversationThreadId", value);

    }
    
        
    private java.util.List<Recipient> newParticipants = null;
    
    
     
    /**
    * Gets the new Participants.
    *
    * @return the java.util.List<Recipient>
    */
    public java.util.List<Recipient> getNewParticipants() {
        return this.newParticipants; 
    }

    /**
    * Sets the new Participants.
    *
    * @param value the java.util.List<Recipient>
    */
    public void setNewParticipants(java.util.List<Recipient> value) { 
        this.newParticipants = value; 
        valueChanged("newParticipants", value);

    }
            
    private String conversationId;
     
    /**
    * Gets the conversation Id.
    *
    * @return the String
    */
    public String getConversationId() {
        return this.conversationId; 
    }

    /**
    * Sets the conversation Id.
    *
    * @param value the String
    */
    public void setConversationId(String value) { 
        this.conversationId = value; 
        valueChanged("conversationId", value);

    }
            
    private Post inReplyTo;
     
    /**
    * Gets the in Reply To.
    *
    * @return the Post
    */
    public Post getInReplyTo() {
        return this.inReplyTo; 
    }

    /**
    * Sets the in Reply To.
    *
    * @param value the Post
    */
    public void setInReplyTo(Post value) { 
        this.inReplyTo = value; 
        valueChanged("inReplyTo", value);

    }
    
        
    private java.util.List<Attachment> attachments = null;
    
    
     
    /**
    * Gets the attachments.
    *
    * @return the java.util.List<Attachment>
    */
    public java.util.List<Attachment> getAttachments() {
        return this.attachments; 
    }

    /**
    * Sets the attachments.
    *
    * @param value the java.util.List<Attachment>
    */
    public void setAttachments(java.util.List<Attachment> value) { 
        this.attachments = value; 
        valueChanged("attachments", value);

    }
}

