/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Corporation. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
package com.microsoft.services.graph;

import com.microsoft.services.orc.core.ODataBaseEntity;




/**
 * The type Recurrence Pattern.
* @deprecated This SDK is deprecated. Please review the README for further information (https://github.com/OfficeDev/Microsoft-Graph-SDK-Android).
 */
@Deprecated
public class RecurrencePattern extends ODataBaseEntity {

    public RecurrencePattern(){
        setODataType("#microsoft.graph.recurrencePattern");
    }

    private RecurrencePatternType type;

    /**
    * Gets the type.
    *
    * @return the RecurrencePatternType
    */
    public RecurrencePatternType getType() {
        return this.type; 
    }

    /**
    * Sets the type.
    *
    * @param value the RecurrencePatternType
    */
    public void setType(RecurrencePatternType value) { 
        this.type = value;
        valueChanged("type", value);

    }

    private Integer interval;

    /**
    * Gets the interval.
    *
    * @return the Integer
    */
    public Integer getInterval() {
        return this.interval; 
    }

    /**
    * Sets the interval.
    *
    * @param value the Integer
    */
    public void setInterval(Integer value) { 
        this.interval = value;
        valueChanged("interval", value);

    }

    private Integer month;

    /**
    * Gets the month.
    *
    * @return the Integer
    */
    public Integer getMonth() {
        return this.month; 
    }

    /**
    * Sets the month.
    *
    * @param value the Integer
    */
    public void setMonth(Integer value) { 
        this.month = value;
        valueChanged("month", value);

    }

    private Integer dayOfMonth;

    /**
    * Gets the day Of Month.
    *
    * @return the Integer
    */
    public Integer getDayOfMonth() {
        return this.dayOfMonth; 
    }

    /**
    * Sets the day Of Month.
    *
    * @param value the Integer
    */
    public void setDayOfMonth(Integer value) { 
        this.dayOfMonth = value;
        valueChanged("dayOfMonth", value);

    }

    private java.util.List<DayOfWeek> daysOfWeek;

    /**
    * Gets the days Of Week.
    *
    * @return the java.util.List<DayOfWeek>
    */
    public java.util.List<DayOfWeek> getDaysOfWeek() {
        return this.daysOfWeek; 
    }

    /**
    * Sets the days Of Week.
    *
    * @param value the java.util.List<DayOfWeek>
    */
    public void setDaysOfWeek(java.util.List<DayOfWeek> value) { 
        this.daysOfWeek = value;
        valueChanged("daysOfWeek", value);

    }

    private DayOfWeek firstDayOfWeek;

    /**
    * Gets the first Day Of Week.
    *
    * @return the DayOfWeek
    */
    public DayOfWeek getFirstDayOfWeek() {
        return this.firstDayOfWeek; 
    }

    /**
    * Sets the first Day Of Week.
    *
    * @param value the DayOfWeek
    */
    public void setFirstDayOfWeek(DayOfWeek value) { 
        this.firstDayOfWeek = value;
        valueChanged("firstDayOfWeek", value);

    }

    private WeekIndex index;

    /**
    * Gets the index.
    *
    * @return the WeekIndex
    */
    public WeekIndex getIndex() {
        return this.index; 
    }

    /**
    * Sets the index.
    *
    * @param value the WeekIndex
    */
    public void setIndex(WeekIndex value) { 
        this.index = value;
        valueChanged("index", value);

    }
}
