/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
package com.microsoft.services.graph;

import com.microsoft.services.orc.core.ODataBaseEntity;




/**
 * The type Recurrence Range.
*/
public class RecurrenceRange extends ODataBaseEntity {

    public RecurrenceRange(){
        setODataType("#microsoft.graph.recurrenceRange");
    }

    private RecurrenceRangeType type;

    /**
    * Gets the type.
    *
    * @return the RecurrenceRangeType
    */
    public RecurrenceRangeType getType() {
        return this.type; 
    }

    /**
    * Sets the type.
    *
    * @param value the RecurrenceRangeType
    */
    public void setType(RecurrenceRangeType value) { 
        this.type = value;
        valueChanged("type", value);

    }

    private java.util.Date startDate;

    /**
    * Gets the start Date.
    *
    * @return the java.util.Date
    */
    public java.util.Date getStartDate() {
        return this.startDate; 
    }

    /**
    * Sets the start Date.
    *
    * @param value the java.util.Date
    */
    public void setStartDate(java.util.Date value) { 
        this.startDate = value;
        valueChanged("startDate", value);

    }

    private java.util.Date endDate;

    /**
    * Gets the end Date.
    *
    * @return the java.util.Date
    */
    public java.util.Date getEndDate() {
        return this.endDate; 
    }

    /**
    * Sets the end Date.
    *
    * @param value the java.util.Date
    */
    public void setEndDate(java.util.Date value) { 
        this.endDate = value;
        valueChanged("endDate", value);

    }

    private String recurrenceTimeZone;

    /**
    * Gets the recurrence Time Zone.
    *
    * @return the String
    */
    public String getRecurrenceTimeZone() {
        return this.recurrenceTimeZone; 
    }

    /**
    * Sets the recurrence Time Zone.
    *
    * @param value the String
    */
    public void setRecurrenceTimeZone(String value) { 
        this.recurrenceTimeZone = value;
        valueChanged("recurrenceTimeZone", value);

    }

    private Integer numberOfOccurrences;

    /**
    * Gets the number Of Occurrences.
    *
    * @return the Integer
    */
    public Integer getNumberOfOccurrences() {
        return this.numberOfOccurrences; 
    }

    /**
    * Sets the number Of Occurrences.
    *
    * @param value the Integer
    */
    public void setNumberOfOccurrences(Integer value) { 
        this.numberOfOccurrences = value;
        valueChanged("numberOfOccurrences", value);

    }
}
