/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Corporation. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
package com.microsoft.services.graph;

import com.microsoft.services.orc.core.ODataBaseEntity;




/**
 * The type Reminder.
*/
public class Reminder extends ODataBaseEntity {

    public Reminder(){
        setODataType("#microsoft.graph.reminder");
    }

    private String eventId;

    /**
    * Gets the event Id.
    *
    * @return the String
    */
    public String getEventId() {
        return this.eventId; 
    }

    /**
    * Sets the event Id.
    *
    * @param value the String
    */
    public void setEventId(String value) { 
        this.eventId = value;
        valueChanged("eventId", value);

    }

    private DateTimeTimeZone eventStartTime;

    /**
    * Gets the event Start Time.
    *
    * @return the DateTimeTimeZone
    */
    public DateTimeTimeZone getEventStartTime() {
        return this.eventStartTime; 
    }

    /**
    * Sets the event Start Time.
    *
    * @param value the DateTimeTimeZone
    */
    public void setEventStartTime(DateTimeTimeZone value) { 
        this.eventStartTime = value;
        valueChanged("eventStartTime", value);

    }

    private DateTimeTimeZone eventEndTime;

    /**
    * Gets the event End Time.
    *
    * @return the DateTimeTimeZone
    */
    public DateTimeTimeZone getEventEndTime() {
        return this.eventEndTime; 
    }

    /**
    * Sets the event End Time.
    *
    * @param value the DateTimeTimeZone
    */
    public void setEventEndTime(DateTimeTimeZone value) { 
        this.eventEndTime = value;
        valueChanged("eventEndTime", value);

    }

    private String changeKey;

    /**
    * Gets the change Key.
    *
    * @return the String
    */
    public String getChangeKey() {
        return this.changeKey; 
    }

    /**
    * Sets the change Key.
    *
    * @param value the String
    */
    public void setChangeKey(String value) { 
        this.changeKey = value;
        valueChanged("changeKey", value);

    }

    private String eventSubject;

    /**
    * Gets the event Subject.
    *
    * @return the String
    */
    public String getEventSubject() {
        return this.eventSubject; 
    }

    /**
    * Sets the event Subject.
    *
    * @param value the String
    */
    public void setEventSubject(String value) { 
        this.eventSubject = value;
        valueChanged("eventSubject", value);

    }

    private Location eventLocation;

    /**
    * Gets the event Location.
    *
    * @return the Location
    */
    public Location getEventLocation() {
        return this.eventLocation; 
    }

    /**
    * Sets the event Location.
    *
    * @param value the Location
    */
    public void setEventLocation(Location value) { 
        this.eventLocation = value;
        valueChanged("eventLocation", value);

    }

    private String eventWebLink;

    /**
    * Gets the event Web Link.
    *
    * @return the String
    */
    public String getEventWebLink() {
        return this.eventWebLink; 
    }

    /**
    * Sets the event Web Link.
    *
    * @param value the String
    */
    public void setEventWebLink(String value) { 
        this.eventWebLink = value;
        valueChanged("eventWebLink", value);

    }

    private DateTimeTimeZone reminderFireTime;

    /**
    * Gets the reminder Fire Time.
    *
    * @return the DateTimeTimeZone
    */
    public DateTimeTimeZone getReminderFireTime() {
        return this.reminderFireTime; 
    }

    /**
    * Sets the reminder Fire Time.
    *
    * @param value the DateTimeTimeZone
    */
    public void setReminderFireTime(DateTimeTimeZone value) { 
        this.reminderFireTime = value;
        valueChanged("reminderFireTime", value);

    }
}
