/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Corporation. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
package com.microsoft.services.graph;

import com.microsoft.services.orc.core.ODataBaseEntity;




/**
 * The type Response Status.
*/
public class ResponseStatus extends ODataBaseEntity {

    public ResponseStatus(){
        setODataType("#microsoft.graph.responseStatus");
    }

    private ResponseType response;

    /**
    * Gets the response.
    *
    * @return the ResponseType
    */
    public ResponseType getResponse() {
        return this.response; 
    }

    /**
    * Sets the response.
    *
    * @param value the ResponseType
    */
    public void setResponse(ResponseType value) { 
        this.response = value;
        valueChanged("response", value);

    }

    private java.util.Calendar time;

    /**
    * Gets the time.
    *
    * @return the java.util.Calendar
    */
    public java.util.Calendar getTime() {
        return this.time; 
    }

    /**
    * Sets the time.
    *
    * @param value the java.util.Calendar
    */
    public void setTime(java.util.Calendar value) { 
        this.time = value;
        valueChanged("time", value);

    }
}
